In [1]:
import torch
import torch.nn as nn

In [10]:
class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        
        #This NN have hidden layer also.
        self.linear1= nn.Linear(num_features, 3)
        self.relu= nn.ReLU()
        self.linear2= nn.Linear(3, 1)
        self.sigmoid= nn.Sigmoid()

    def forward(self, features):

        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [11]:
features = torch.rand(10, 5)

model = Model(features.shape[1])

model(features)

tensor([[0.3697],
        [0.3847],
        [0.3733],
        [0.3719],
        [0.3654],
        [0.3737],
        [0.3739],
        [0.3826],
        [0.3686],
        [0.3782]], grad_fn=<SigmoidBackward0>)

In [12]:
model.linear1.weight

Parameter containing:
tensor([[-0.4256, -0.2205,  0.3319, -0.3399, -0.3006],
        [ 0.3467,  0.3383,  0.3235,  0.0754, -0.2865],
        [ 0.4114, -0.0105,  0.1661,  0.3777,  0.2577]], requires_grad=True)

In [13]:
model.linear2.weight

Parameter containing:
tensor([[-0.2088,  0.0233, -0.1457]], requires_grad=True)

In [14]:
model.linear1.bias

Parameter containing:
tensor([ 0.4449, -0.2525,  0.2525], requires_grad=True)

In [15]:
model.linear2.bias

Parameter containing:
tensor([-0.3812], requires_grad=True)

In [16]:
!pip install torchinfo


[notice] A new release of pip is available: 24.2 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [17]:
from torchinfo import summary
summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00